version: '3'

services:
  django: {% if cookiecutter.use_celery.lower() == 'y' %}&django{% endif %}
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: {{ cookiecutter.project_slug }}_local_django
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      {%- if cookiecutter.local_sgbd.lower() == 'postgres' %}
      - ./.envs/.local/.postgres
      {%- endif %}
      {%- if cookiecutter.local_sgbd.lower() == 'mssql' %}
      - ./.envs/.local/.mssql
      {%- endif %}
    {%- if cookiecutter.local_sgbd.lower() != 'sqllite' %}
    depends_on:
    {%- endif %}
    {%- if cookiecutter.local_sgbd.lower() == 'postgres' %}
      - postgres
    {%- endif %}
    {%- if cookiecutter.local_sgbd.lower() == 'mssql' %}
      - mssql
    {%- endif %}
    ports:
      - "8000:8000"

{%- if cookiecutter.local_sgbd.lower() == 'postgres' %}

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: {{ cookiecutter.project_slug }}_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

{%- endif %}

{%- if cookiecutter.local_sgbd.lower() == 'mssql' %}

  mssql:
    build:
      context: .
      dockerfile: ./compose/local/mssql/Dockerfile
    image: {{ cookiecutter.project_slug }}_local_mssql
    environment:
      SA_PASSWORD: "!MSSQL2017_{{ cookiecutter.project_slug }}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

{%- endif %}

{% if cookiecutter.use_celery.lower() == 'y' %}
  redis:
    image: redis:6.0
    container_name: redis-dev

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog-dev
    ports:
      - "8025:8025"

  celeryworker:
    <<: *django
    image: sophia_local_celeryworker
    container_name: celeryworker-dev
    depends_on:
      - redis
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: sophia_local_celerybeat
    container_name: celerybeat-dev
    depends_on:
      - redis
      - mailhog
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: sophia_local_flower
    container_name: flower-dev
    ports:
      - "5555:5555"
    command: /start-flower
{% endif %}
