version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: {{ cookiecutter.project_slug }}_local_django
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      {%- if cookiecutter.local_sgbd.lower() == 'postgres' %}
      - ./.envs/.local/.postgres
      {%- endif %}
    ports:
      - "8000:8000"
    command: /start

{%- if cookiecutter.local_sgbd.lower() == 'postgres' %}

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: {{ cookiecutter.project_slug }}_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

{%- endif %}
