version: '3'

volumes:
  production_django: {}

services:

  redis:
    image: redis:3.2

  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: mapariscos_production_django
    depends_on:
      - redis
    volumes:
      - production_django:/app
    env_file:
      - ./.envs/.production/.django
      {%- if cookiecutter.local_sgbd.lower() == 'postgres' %}
      - ./.envs/.production/.postgres
      {%- endif %}
    ports:
      - "5000:5000"
    command: /start

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: mapariscos_production_nginx
    depends_on:
      - django
    volumes:
      - production_django:/app
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

{%- if cookiecutter.production_sgbd.lower() == 'postgres' %}

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: {{ cookiecutter.project_slug }}_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

{%- endif %}
